repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      args: [
        --line-length=80, 
        --target-version=py38
      ]
      exclude: ^(venv/|docs/)
      types: ['python']
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 3.8.2
  #   hooks:
  #   - id: flake8
  #     args: [
  #       --max-line-length=90
  #     ]
  #     exclude: ^(venv/|docs/)
  #     types: ['python']