LEAGUE_TABLE_COLUMNS = [
    "Rk",
    "Squad",
    "MP",
    "W",
    "D",
    "L",
    "GF",
    "GA",
    "GD",
    "Pts",
    "Home_MP",
    "Home_W",
    "Home_D",
    "Home_L",
    "Home_GF",
    "Home_GA",
    "Home_GD",
    "Home_Pts",
    "Home_Pts/MP",
    "Away_MP",
    "Away_W",
    "Away_D",
    "Away_L",
    "Away_GF",
    "Away_GA",
    "Away_GD",
    "Away_Pts",
    "Away_Pts/MP",
]

# FBref columns of interest

# Fixture table columns
FIXTURE_TABLE_COLUMNS = [
    "week",
    "dow",
    "kickoff",
    "home_team",
    "home_score",
    "away_score",
    "xG_home",
    "xG_away",
    "away_team",
    "attendance",
    "referee",
    "notes",
]

# Attacking rename column dictionary

ATTACKING_RENAME_COL_DICT = {
    "#_Pl": "no_of_players_used",
    "Expected_xG_x": "Expected_xG",
    "Expected_npxG_x": "Expected_npxG",
    "Poss": "possession",
    "Playing_Time_MP": "MP",
    "Performance_Gls": "total_goals",
    "Performance_Ast": "total_assists",
    "Performance_G_minus_PK": "total_non_penalty_goals",
    "Performance_PK": "total_penalties",
    "Performance_PKatt": "total_penalty_attempted",
    "Per_90_Minutes_Gls": "total_goals_per_90",
    "Per_90_Minutes_Ast": "total_assist_per_90",
    "Per_90_Minutes_G_minus_PK": "total_non_penalty_goals_per_90",
    "Expected_xG_x": "total_xg",
    "Expected_npxG_x": "total_npxg",
    "Expected_xAG": "total_expected_assisted_goals",
    "Per_90_Minutes_xG": "total_xg_per_90",
    "Per_90_Minutes_xAG": "total_expected_assisted_goals_per_90",
    "Per_90_Minutes_npxG": "total_npxg_per_90",
    "Standard_Sh": "total_shots",
    "Standard_SoT": "total_shots_on_target",
    "Standard_SoT_perc": "shot_on_target_perc",
    "Standard_Sh_per_90": "total_shots_per_90",
    "Standard_SoT_per_90": "total_shots_on_target_per_90",
    "Standard_G_per_Sh": "goal_per_shot",
    "Standard_G_per_SoT": "goal_per_shot_on_target",
    "Standard_Dist": "average_distance_per_shot",
    "Standard_FK": "total_shots_free_kicks",
    "Standard_PK": "total_penalties_scored",
    "Standard_PKatt": "total_penalties_attempted",
    "Expected_npxG_per_Sh": "npxG_per_Sh",
    "Expected_G_minus_xG": "total_goals_minus_xg",
    "Expected_np:G_minus_xG": "total_npg_minus_npxg",
    "SCA_SCA": "total_sca",
    "SCA_SCA90": "total_sca_per_90",
    "SCA_Types_PassLive": "total_live_ball_passes_to_shots",
    "SCA_Types_PassDead": "total_dead_ball_passes_to_shots",
    "SCA_Types_Drib": "total_successful_dribbles_to_shots",
    "SCA_Types_Sh": "total_shots_to_shots",
    "SCA_Types_Fld": "total_fouls_drawn_to_shots",
    "SCA_Types_Def": "total_defensive_actions_to_shots",
    "GCA_GCA": "total_gca",
    "GCA_GCA90": "total_gca_per_90",
    "GCA_Types_PassLive": "total_live_ball_passes_to_goals",
    "GCA_Types_PassDead": "total_dead_ball_passes_to_goals",
    "GCA_Types_Drib": "total_successful_dribbles_to_goals",
    "GCA_Types_Sh": "total_shots_to_goals",
    "GCA_Types_Fld": "total_fouls_drawn_to_goals",
    "GCA_Types_Def": "total_defensive_actions_to_goals",
}

# Attacking total columns

ATTACKING_TOTAL_COLUMNS = [
    "total_goals",
    "total_assists",
    "total_non_penalty_goals",
    "total_penalties",
    "total_penalty_attempted",
    "total_xg",
    "total_npxg",
    "total_expected_assisted_goals",
    "Expected_npxG_plus_xAG",
    "total_shots",
    "total_shots_on_target",
    "total_shots_free_kicks",
    "total_penalties_scored",
    "total_penalties_attempted",
    "total_goals_minus_xg",
    "total_npg_minus_npxg",
    "total_sca",
    "total_live_ball_passes_to_shots",
    "total_dead_ball_passes_to_shots",
    "total_successful_dribbles_to_shots",
    "total_shots_to_shots",
    "total_fouls_drawn_to_shots",
    "total_defensive_actions_to_shots",
    "total_gca",
    "total_live_ball_passes_to_goals",
    "total_dead_ball_passes_to_goals",
    "total_successful_dribbles_to_goals",
    "total_shots_to_goals",
    "total_fouls_drawn_to_shots",
    "total_defensive_actions_to_shots",
]

# Defense rename column dictionary
DEFENSE_RENAME_COL_DICT = {
    "#_Pl": "no_of_players_used",
    "90s": "MP",
    "Tackles_Tkl": "total_tackles",
    "Tackles_TklW": "total_tackles_won",
    "Tackles_Def_3rd": "total_tackles_won_d3",
    "Tackles_Mid_3rd": "total_tackles_won_m3",
    "Tackles_Att_3rd": "total_tackles_won_a3",
    "Vs_Dribbles_Tkl": "total_dribbles_tackled",
    "Vs_Dribbles_Att": "total_dribbles_faced",
    "Vs_Dribbles_Tkl_perc": "dribbles_tackled_perc",
    "Vs_Dribbles_Past": "total_dribbles_past",
    "Blocks_Blocks": "total_blocks",
    "Blocks_Sh": "total_shots_blocked",
    "Blocks_Pass": "total_shots_passed",
    "Int": "total_interceptions",
    "Tkl_plus_Int": "total_tackles_interceptions",
    "Clr": "total_clearances",
    "Err": "total_errors_to_opp_shots",
    "Performance_CrdY": "total_yellow_cards",
    "Performance_CrdR": "total_red_cards",
    "Performance_2CrdY": "total_second_yellows",
    "Performance_Fls": "total_fouls_committed",
    "Performance_Fld": "total_fouls_drawn",
    "Performance_Off": "total_offsides",
    "Performance_Crs": "total_crosses",
    "Performance_PKwon": "total_penalties_won",
    "Performance_PKcon": "total_penalties_conceded",
    "Performance_OG": "total_own_goals",
    "Performance_Recov": "total_loose_balls_recovered",
    "Aerial_Duels_Won": "total_aerial_duels_won",
    "Aerial_Duels_Lost": "total_aerial_duels_lost",
    "Aerial_Duels_Won%": "aeriel_duels_perc",
}

# Defense total columns
DEFENSE_TOTAL_COLUMNS = [
    "total_tackles",
    "total_tackles_won",
    "total_tackles_won_d3",
    "total_tackles_won_m3",
    "total_tackles_won_a3",
    "total_dribbles_tackled",
    "total_dribbles_faced",
    "total_dribbles_past",
    "total_blocks",
    "total_shots_blocked",
    "total_shots_passed",
    "total_interceptions",
    "total_tackles_interceptions",
    "total_clearances",
    "total_yellow_cards",
    "total_red_cards",
    "total_second_yellows",
    "total_fouls_committed",
    "total_fouls_drawn",
    "total_offsides",
    "total_crosses",
    "total_penalties_won",
    "total_penalties_conceded",
    "total_own_goals",
    "total_loose_balls_recovered",
    "total_aerial_duels_won",
    "total_aerial_duels_lost",
]


# Passing rename column dictionary
PASSING_RENAME_COL_DICT = {
    "#_Pl": "no_of_players_used",
    "90s": "MP",
    "Cmp": "total_passes_completed",
    "Total_Cmp": "total_passes_completed",  # 2022/2023
    "Total_Att": "total_passes_attempted",
    "Total_Cmp_perc": "pass_completion_perc",
    "Total_TotDist": "distance_covered",
    "Total_PrgDist": "progressive_distance",  # towards to opponents goal
    "Short_Cmp": "total_short_passes_completed",  # 5-15 yards
    "Short_Att": "total_short_passes_attempted",
    "Short_Cmp_perc": "short_pass_completion_perc",
    "Medium_Cmp": "total_medium_passes_completed",  # 15-30 yards
    "Medium_Att": "total_medium_passes_attempted",
    "Medium_Cmp_perc": "medium_pass_completion_perc",
    "Long_Cmp": "total_long_passes_completed",
    "Long_Att": "total_long_passes_attempted",
    "Long_Cmp_perc": "long_pass_completion_perc",
    "KP": "total_key_passes",  # passes that lead to a shot
    "1_per_3": "total_completed_final_third_passes",  # set pieces not included
    "PPA": "total_completed_18_yard_box_passes",  # set pieces not included
    "CrsPA": "total_completed_18_yard_box_crosses",
    "Prog": "total_progressive_passes",
    "Pass_Types_Live": "total_live_ball_passes",
    "Pass_Types_Dead": "total_dead_ball_passes",
    "Pass_Types_FK": "free_kick_passes_attempted",
    "Pass_Types_TB": "defence_to_open_space_passes_completed",
    "Pass_Types_Sw": "passes_40_yards_width",
    "Pass_Types_Crs": "total_crosses",
    "Pass_Types_TI": "total_throw_in_taken",
    "Pass_Types_CK": "total_corners",
    "Corner_Kicks_In": "total_inswinging_corners",
    "Corner_Kicks_Out": "total_outswinging_corners",
    "Corner_Kicks_Str": "total_straight_corners",
    "Outcomes_Off": "total_passes_offsides",
    "Outcomes_Blocks": "total_passes_blocked",
    "Poss": "possession",
    "Touches_Touches": "total_touches",
    "Touches_Def_Pen": "defensive_penalty_area_touches",
    "Touches_Def_3rd": "defensive_third_touches",
    "Touches_Mid_3rd": "middle_third_touches",
    "Touches_Att_3rd": "attacking_third_touches",
    "Touches_Att_Pen": "attacking_penalty_area_touches",
    "Touches_Live": "total_live_ball_touches",
    "Dribbles_Succ": "total_dribbles_completed",
    "Dribbles_Att": "total_dribble_attempted",
    "Dribbles_Succ_perc": "dribbles_success_perc",
    "Dribbles_Mis": "dribbles_unsuccessful_dispossession",
    "Dribbles_Dis": "dribbles_dispossesed",
    "Receiving_Rec": "total_passes_recieved",
    "Receiving_Prog": "total_progressive_passes_recieved",
}


# passing total columns

PASSING_TOTAL_COLUMNS = [
    "total_passes_completed",
    "total_passes_attempted",
    "distance_covered",
    "progressive_distance",
    "total_short_passes_completed",
    "total_short_passes_attempted",
    "total_medium_passes_completed",
    "total_medium_passes_attempted",
    "total_long_passes_completed",
    "total_long_passes_attempted",
    "total_key_passes",
    "total_completed_final_third_passes",
    "total_completed_18_yard_box_passes",
    "total_completed_18_yard_box_crosses",
    "total_progressive_passes",
    "total_live_ball_passes",
    "total_dead_ball_passes",
    "free_kick_passes_attempted",
    "defence_to_open_space_passes_completed",
    "passes_40_yards_width",
    "total_crosses",
    "total_throw_in_taken",
    "total_corners",
    "total_inswinging_corners",
    "total_outswinging_corners",
    "total_straight_corners",
    "total_passes_offsides",
    "total_passes_blocked",
    "total_touches",
    "defensive_penalty_area_touches",
    "defensive_third_touches",
    "middle_third_touches",
    "attacking_third_touches",
    "attacking_penalty_area_touches",
    "total_live_ball_touches",
    "total_dribbles_completed",
    "total_dribble_attempted",
    "dribbles_success_perc",
    "dribbles_unsuccessful_dispossession",
    "dribbles_dispossesed",
    "total_passes_recieved",
    "total_progressive_passes_recieved",
]

# Goalkeeping rename column dictionary
GOALKEEPING_RENAME_COL_DICT = {
    "#_Pl": "no_of_players_used",
    "Playing_Time_MP": "MP",
    "Performance_GA": "total_goals_against",
    "Performance_GA90": "total_goals_against_per_90",
    "Performance_SoTA": "total_shots_on_target_against",
    "Performance_Saves": "total_saves",
    "Performance_Save_perc": "save_perc",
    "Performance_CS": "total_clean_sheets",
    "Performance_CS_perc": "clean_sheet_perc",
    "Penalty_Kicks_PKatt": "total_penalties_faced",
    "Penalty_Kicks_PKA": "total_penalties_allowed",
    "Penalty_Kicks_PKsv": "total_penalties_saved",
    "Penalty_Kicks_PKm": "total_penalties_missed",
    "Penalty_Kicks_Save_perc": "penalty_save_perc",
    "Goals_PKA": "total_goals_against_penalties",
    "Goals_FK": "total_goals_against_free_kicks",
    "Goals_CK": "total_goals_against_corners",
    "Goals_OG": "total_goals_against_own_goals",
    "Expected_PSxG": "total_post_shot_xg",
    "Expected_PSxG_per_SoT": "total_post_shot_xg_per_shot_on_target",
    "Expected_PSxG_plus__per__minus_": "post_shot_xg_minus_goals_against",
    "Expected__per_90": "post_shot_xg_minus_goals_against_per_90",
    "Launched_Cmp": "total_40_yard_passes_completed",
    "Launched_Att": "total_40_yard_passes_attempted",
    "Launched_Cmp_perc": "total_40_yard_passes_completion_perc",
    "Passes_Att": "total_passes_attempted_excl_goal_kick",
    "Passes_Thr": "total_throws_attempted",
    "Passes_Launch_perc": "total_passes_lauches_perc_excl_goal_kick",
    "Passes_AvgLen": "average_pass_length_excl_goal_kick",
    "Goal_Kicks_Att": "goal_kicks_attempted",
    "Goal_Kicks_Launch_perc": "goal_kicks_launched_perc",
    "Goal_Kicks_AvgLen": "average_goal_kicks_length",
    "Crosses_Opp": "opponent_attempted_crosses_into_penalty_area",
    "Crosses_Stp": "opponent_crosses_into_penalty_area_stopped",
    "Crosses_Stp_perc": "opponent_crosses_into_penalty_area_stopped_perc",
    "Sweeper_#OPA": "defensive_actions_outside_penalty_area",
    "Sweeper_#OPA_per_90": "defensive_actions_outside_penalty_area_per_90",
    "Sweeper_AvgDist": "average_distance_from_goal_for_defensive_actions",
}

# Goalkeeping total columns
GOALKEEPING_TOTAL_COLUMNS = [
    "total_shots_on_target_against",
    "total_saves",
    "total_goals_against",
    "total_goals_against_penalties",
    "total_goals_against_free_kicks",
    "total_goals_against_corners",
    "total_goals_against_own_goals",
    "total_post_shot_xg",
    "total_40_yard_passes_completed",
    "total_40_yard_passes_attempted",
    "total_passes_attempted_excl_goal_kick",
    "total_throws_attempted",
    "total_passes_lauches_perc_excl_goal_kick",
    "average_pass_length_excl_goal_kick",
    "goal_kicks_attempted",
    "opponent_attempted_crosses_into_penalty_area",
    "opponent_crosses_into_penalty_area_stopped",
    "defensive_actions_outside_penalty_area",
]

# Playing time rename column dictionary
PLAYING_TIME_RENAME_COL_DICT = {
    "#_Pl": "no_of_players_used",
    "Age": "average_age",
    "Playing_Time_MP": "MP",
    "Subs_Subs": "no_of_subs_used",
    "Subs_Mn_per_Sub": "minutes_per_sub",
    "Subs_unSub": "no_of_subs_unused",
    "Team_Success__plus__per__minus_90": "goals_scored_minus_against_per_90",
    "Team_Success_(xG)_onxG": "total_expect_goals",
    "Team_Success_(xG)_onxGA": "total_expected_goals_against",
    "Team_Success_(xG)_xG_plus__per__minus_": "xg_minus_xga",
    "Team_Success_(xG)_xG_plus__per__minus_90": "xg_minus_xga_per_90",
}

# Playing time total columns
PLAYING_TIME_TOTAL_COLUMNS = [
    "no_of_subs_used",
    "no_of_subs_unused",
    "total_expect_goals",
    "total_expected_goals_against",
]

# comparison columns

ATTACKING_COMPARISON_COLUMNS = [
    "possession",
    "MP",
    "total_goals",
    "total_assists",
    "total_non_penalty_goals",
    "total_penalties",
    "total_goals_per_match",
    "total_assists_per_match",
    "total_non_penalty_goals_per_match",
    "total_penalties_per_match",
    "total_penalty_attempted_per_match",
    "total_xg_per_match",
    "total_npxg_per_match",
    "total_expected_assisted_goals_per_match",
    "total_shots_per_match",
    "total_shots_on_target_per_match",
    "total_shots_free_kicks_per_match",
    "goal_per_shot_on_target",
    "average_distance_per_shot",
    "total_penalties_scored_per_match",
    "total_penalties_attempted_per_match",
    "total_goals_minus_xg_per_match",
    "total_npg_minus_npxg_per_match",
    "total_sca_per_match",
    "total_live_ball_passes_to_shots_per_match",
    "total_dead_ball_passes_to_shots_per_match",
    "total_successful_dribbles_to_shots_per_match",
    "total_shots_to_shots_per_match",
    "total_fouls_drawn_to_shots_per_match",
    "total_defensive_actions_to_shots_per_match",
    "total_gca_per_match",
    "total_live_ball_passes_to_goals_per_match",
    "total_dead_ball_passes_to_goals_per_match",
    "total_successful_dribbles_to_goals_per_match",
    "total_shots_to_goals_per_match",
    "goal_to_assist_ratio",
]

DEFENSE_COMPARISON_COLUMNS = [
    "dribbles_tackled_perc",
    "total_penalties_conceded",
    "total_own_goals",
    "Aerial_Duels_Won_perc",
    "total_tackles_per_match",
    "total_tackles_won_per_match",
    "total_tackles_won_d3_per_match",
    "total_tackles_won_m3_per_match",
    "total_tackles_won_a3_per_match",
    "total_dribbles_tackled_per_match",
    "total_dribbles_faced_per_match",
    "total_dribbles_past_per_match",
    "total_blocks_per_match",
    "total_shots_blocked_per_match",
    "total_shots_passed_per_match",
    "total_interceptions_per_match",
    "total_tackles_interceptions_per_match",
    "total_clearances_per_match",
    "total_yellow_cards_per_match",
    "total_red_cards_per_match",
    "total_second_yellows_per_match",
    "total_fouls_committed_per_match",
    "total_fouls_drawn_per_match",
    "total_offsides_per_match",
    "total_crosses_per_match",
    "total_penalties_won_per_match",
    "total_penalties_conceded_per_match",
    "total_own_goals_per_match",
    "total_loose_balls_recovered_per_match",
    "total_aerial_duels_won_per_match",
    "total_aerial_duels_lost_per_match",
]

PASSING_COMPARISON_COLUMNS = [
    "MP",
    "possession",
    "pass_completion_perc",
    "short_pass_completion_perc",
    "medium_pass_completion_perc",
    "long_pass_completion_perc",
    "total_corners",
    "total_inswinging_corners",
    "total_outswinging_corners",
    "total_straight_corners",
    "dribbles_success_perc",
    "total_passes_completed_per_match",
    "total_passes_attempted_per_match",
    "distance_covered_per_match",
    "progressive_distance_per_match",
    "total_short_passes_completed_per_match",
    "total_short_passes_attempted_per_match",
    "total_medium_passes_completed_per_match",
    "total_medium_passes_attempted_per_match",
    "total_long_passes_completed_per_match",
    "total_long_passes_attempted_per_match",
    "total_key_passes_per_match",
    "total_completed_final_third_passes_per_match",
    "total_completed_18_yard_box_passes_per_match",
    "total_completed_18_yard_box_crosses_per_match",
    "total_progressive_passes_per_match",
    "total_live_ball_passes_per_match",
    "total_dead_ball_passes_per_match",
    "free_kick_passes_attempted_per_match",
    "defence_to_open_space_passes_completed_per_match",
    "passes_40_yards_width_per_match",
    "total_crosses_per_match",
    "total_throw_in_taken_per_match",
    "total_corners_per_match",
    "total_inswinging_corners_per_match",
    "total_outswinging_corners_per_match",
    "total_straight_corners_per_match",
    "total_passes_offsides_per_match",
    "total_passes_blocked_per_match",
    "total_touches_per_match",
    "defensive_penalty_area_touches_per_match",
    "defensive_third_touches_per_match",
    "middle_third_touches_per_match",
    "attacking_third_touches_per_match",
    "attacking_penalty_area_touches_per_match",
    "total_live_ball_touches_per_match",
    "total_dribbles_completed_per_match",
    "total_dribble_attempted_per_match",
    "dribbles_success_perc_per_match",
    "dribbles_unsuccessful_dispossession_per_match",
    "dribbles_dispossesed_per_match",
    "total_passes_recieved_per_match",
    "total_progressive_passes_recieved_per_match",
]

GOALKEEPING_COMPARISON_COLUMNS = [
    "no_of_players_used",
    "MP",
    "total_goals_against",
    "total_goals_against_per_90",
    "save_perc",
    "total_clean_sheets",
    "clean_sheet_perc",
    "total_penalties_faced",
    "total_penalties_allowed",
    "total_penalties_saved",
    "total_penalties_missed",
    "penalty_save_perc",
    "total_goals_against_penalties",
    "total_goals_against_free_kicks",
    "total_goals_against_corners",
    "total_goals_against_own_goals",
    "total_post_shot_xg",
    "total_post_shot_xg_per_shot_on_target",
    "post_shot_xg_minus_goals_against_per_90",
    "total_40_yard_passes_completion_perc",
    "total_passes_lauches_perc_excl_goal_kick",
    "average_pass_length_excl_goal_kick",
    "goal_kicks_launched_perc",
    "average_goal_kicks_length",
    "opponent_crosses_into_penalty_area_stopped_perc",
    "defensive_actions_outside_penalty_area_per_90",
    "average_distance_from_goal_for_defensive_actions",
    "total_shots_on_target_against_per_match",
    "total_saves_per_match",
    "total_goals_against_per_match",
    "total_goals_against_penalties_per_match",
    "total_goals_against_free_kicks_per_match",
    "total_goals_against_corners_per_match",
    "total_goals_against_own_goals_per_match",
    "total_post_shot_xg_per_match",
    "total_40_yard_passes_completed_per_match",
    "total_40_yard_passes_attempted_per_match",
    "total_passes_attempted_excl_goal_kick_per_match",
    "total_throws_attempted_per_match",
    "total_passes_lauches_perc_excl_goal_kick_per_match",
    "average_pass_length_excl_goal_kick_per_match",
    "goal_kicks_attempted_per_match",
    "opponent_attempted_crosses_into_penalty_area_per_match",
    "opponent_crosses_into_penalty_area_stopped_per_match",
    "defensive_actions_outside_penalty_area_per_match",
]

PLAYING_COMPARISON_COLUMNS = [
    "MP",
    "minutes_per_sub",
    "goals_scored_minus_against_per_90",
    "xg_minus_xga_per_90",
    "no_of_subs_used_per_match",
    "no_of_subs_unused_per_match",
    "total_expect_goals_per_match",
    "total_expected_goals_against_per_match",
]
